---
title: "practical_exercise_10 , Methods 3, 2021, autumn semester"
author: 'Linus Backström'
date: "8.12.2021"
output: pdf_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

```{python}
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.decomposition import PCA
```


# Exercises and objectives

1) Use principal component analysis to improve the classification of subjective experience  
2) Use logistic regression with cross-validation to find the optimal number of principal components  


REMEMBER: In your report, make sure to include code that can reproduce the answers requested in the exercises below (__MAKE A KNITTED VERSION__)  
REMEMBER: This is Assignment 4 and will be part of your final portfolio   

# EXERCISE 1 - Use principal component analysis to improve the classification of subjective experience  

We will use the same files as we did in Assignment 3
The files `megmag_data.npy` and `pas_vector.npy` can be downloaded here (http://laumollerandersen.org/data_methods_3/megmag_data.npy) and here (http://laumollerandersen.org/data_methods_3/pas_vector.npy)  
The function `equalize_targets` is supplied - this time, we will only work with an equalized data set. One motivation for this is that we have a well-defined chance level that we can compare against. Furthermore, we will look at a single time point to decrease the dimensionality of the problem  

1) Create a covariance matrix, find the eigenvectors and the eigenvalues
    i. Load `megmag_data.npy` and call it `data` using `np.load`. You can use `join`, which can be imported from `os.path`, to create paths from different string segments 
    
```{python}
data = np.load('C:/Users/linus/Documents/GitHub/github_methods_3/week_10/megmag_data.npy')
y = np.load('C:/Users/linus/Documents/GitHub/github_methods_3/week_10/pas_vector.npy')
```
    
    ii. Equalize the number of targets in `y` and `data` using `equalize_targets` 
    
```{python}
def equalize_targets(data, y):
    np.random.seed(7)
    targets = np.unique(y)
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target))
        indices.append(np.where(y == target)[0])
    min_count = np.min(counts)
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count, replace=False)
    third_choice = np.random.choice(indices[2], size=min_count, replace=False)
    fourth_choice = np.random.choice(indices[3], size=min_count, replace=False)
    
    new_indices = np.concatenate((first_choice, second_choice,
                                 third_choice, fourth_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y
    
eq = equalize_targets(data, y)

X_all_eq = eq[0]
y_all_eq = eq[1]
```
    
    iii. Construct `times=np.arange(-200, 804, 4)` and find the index corresponding to 248 ms - then reduce the dimensionality of `data` from three to two dimensions by only choosing the time index corresponding to 248 ms (248 ms was where we found the maximal average response in Assignment 3) 
    
```{python}
import numpy as np

times = np.arange(-200, 804, 4)

times[112] # 248 ms

X_all_eq.shape  # (396, 102, 251)

X_eq_rdc = X_all_eq[:, :, times[112]]
```
    
    iv. Scale the data using `StandardScaler`  
    
```{python}
from sklearn.preprocessing import StandardScaler

scaledata = StandardScaler()

X_eq_rdc_sc = scaledata.fit_transform(X_eq_rdc)
```
    
    v. Calculate the sample covariance matrix for the sensors (you can use `np.cov`) and plot it (either using `plt.imshow` or `sns.heatmap` (`import seaborn as sns`))  
    
```{python}
cov_mat = np.cov(X_eq_rdc_sc, rowvar = False) # rowvar because our rows and columns are a certain way

#We now plot the confusion matrix
import seaborn as sns
plt.figure()
heatmap = sns.heatmap(cov_mat, square=True)
heatmap.set_title('Confusion Matrix');
plt.show()
```
    
    vi. What does the off-diagonal activation imply about the independence of the signals measured by the 102 sensors?  
    
  It implies that the sensors are not completely independent of each other.
    
    vii. Run `np.linalg.matrix_rank` on the covariance matrix - what integer value do you get? (we'll use this later)  
    
```{python}
np.linalg.matrix_rank(cov_mat) # 97, i.e. 5 sensors are completely linearly dependent of some other sensor
```
  
    
    viii. Find the eigenvalues and eigenvectors of the covariance matrix using `np.linalg.eig` - note that some of the numbers returned are complex numbers, consisting of a real and an imaginary part (they have a _j_ next to them). We are going to ignore this by only looking at the real parts of the eigenvectors and -values. Use `np.real` to retrieve only the real parts  
    
```{python}
eig_val, eig_vec = np.linalg.eig(cov_mat)

eig_val = np.real(eig_val)
eig_vec = np.real(eig_vec)
```
    
2) Create the weighting matrix $W$ and the projected data, $Z$
    i. We need to sort the eigenvectors and eigenvalues according to the absolute values of the eigenvalues (use `np.abs` on the eigenvalues).  
    
```{python}
eig_val_abs = np.abs(eig_val)
```
    
    ii. Then, we will find the correct ordering of the indices and create an array, e.g. `sorted_indices` that contains these indices. We want to sort the values from highest to lowest. For that, use `np.argsort`, which will find the indices that correspond to sorting the values from lowest to highest. Subsequently, use `np.flip`, which will reverse the order of the indices.   
    
```{python}
sorted_indices = np.argsort(eig_val_abs)
sorted_indices = np.flip(sorted_indices)
```
    
    iii. Finally, create arrays of sorted eigenvalues and eigenvectors using the `sorted_indices` array just created. For the eigenvalues, it should like this `eigenvalues = eigenvalues[sorted_indices]` and for the eigenvectors: `eigenvectors = eigenvectors[:, sorted_indices]`
    
```{python}
eigenvalues = eig_val[sorted_indices]
eigenvectors = eig_vec[:, sorted_indices]
```
    
    iv. Plot the log, `np.log`, of the eigenvalues, `plt.plot(np.log(eigenvalues), 'o')` - are there some values that stand out from the rest? In fact, 5 (noise) dimensions have already been projected out of the data - how does that relate to the matrix rank (Exercise 1.1.vii)  
    
```{python}
plt.figure()
plt.plot(np.log(eigenvalues), 'o')
plt.show()
```
    
Two values are much lower than the rest, signifying eigenvalues that are very close to zero, which results in a negative value of around -35 for the log of the eigenvalues.    
    
    v. Create the weighting matrix, `W` (it is the sorted eigenvectors)  
    
```{python}
W = eigenvectors
```
    
    vi. Create the projected data, `Z`, $Z = XW$ - (you can check you did everything right by checking whether the $X$ you get from $X = ZW^T$ is equal to your original $X$, `np.isclose` may be of help)
    
```{python}
Z = X_eq_rdc_sc @ W

np.isclose(Z @ W.T, X_eq_rdc_sc) # it matches!

```
    
    vii. Create a new covariance matrix of the principal components (n=102) - plot it! What has happened off-diagonal and why?

```{python}
cov_mat2 = np.cov(Z, rowvar = False) # rowvar because our rows and columns are a certain way

#We now plot the confusion matrix
import seaborn as sns
plt.figure()
heatmap = sns.heatmap(cov_mat2, square=True)
heatmap.set_title('Confusion Matrix');
plt.show()
```

There appears to be no collinearity on the off-diagonal.

# EXERCISE 2 - Use logistic regression with cross-validation to find the optimal number of principal components  

1) We are going to run logistic regression with in-sample validation 
    i. First, run standard logistic regression (no regularization) based on $Z_{d \times k}$ and `y` (the target vector). Fit (`.fit`) 102 models based on: $k = [1, 2, ..., 101, 102]$ and $d = 102$. For each fit get the classification accuracy, (`.score`), when applied to $Z_{d \times k}$ and $y$. This is an in-sample validation. Use the solver `newton-cg` if the default solver doesn't converge
    
```{python}
from sklearn.linear_model import LogisticRegression

Z.shape # 396, 102

log_reg = LogisticRegression(penalty='none', solver='newton-cg')

scores = np.zeros(shape=(102))

for i in range(102):
    if i == 0:
        X = Z[:, 0]
        X = X.reshape(-1, 1)
    elif i == 102:
        X = Z[:, 0]
    else:
        X = Z[:, 0:i+1]
    log_model = log_reg.fit(X, y_all_eq)
    score = log_model.score(X, y_all_eq)
    scores[i] = score

scores  
```
    
    ii. Make a plot with the number of principal components on the _x_-axis and classification accuracy on the _y_-axis - what is the general trend and why is this so?
    
```{python}
plt.figure()
plt.plot(scores)
plt.xlabel('Number of principal components')
plt.ylabel('Classification accuracy')
plt.show()
```
    
We can observe that the number of principal components increases classification accuracy, with diminishing returns. More principal components means more information to base the classification upon. Diminishing returns occurs because we have ordered the principal components so that the most impactful ones are first.    
    
    iii. In terms of classification accuracy, what is the effect of adding the five last components? Why do you think this is so?
    
The last five components do not increase the accuracy at all, because they are dependent on other components and therefore do not add extra information to help with the classification.

2) Now, we are going to use cross-validation - we are using `cross_val_score` and `StratifiedKFold` from `sklearn.model_selection`

```{python}
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
```

    i. Define the variable: `cv = StratifiedKFold()` and run `cross_val_score` (remember to set the `cv` argument to your created `cv` variable). Use the same `estimator` in `cross_val_score` as in Exercise 2.1.i. Find the mean score over the 5 folds (the default of `StratifiedKFold`) for each $k$, $k = [1, 2, ..., 101, 102]$  
    
```{python}
log_reg = LogisticRegression(penalty='none', solver='newton-cg')

cv = StratifiedKFold(n_splits = 5)

scores = np.zeros(shape=(102))

for i in range(102):
    if i == 0:
        X = Z[:, 0]
        X = X.reshape(-1, 1)
    elif i == 102:
        X = Z[:, 0]
    else:
        X = Z[:, 0:i+1]
    log_model = log_reg.fit(X, y_all_eq)
    score = cross_val_score(log_model, X, y_all_eq, cv=cv)
    mean = np.mean(score)
    scores[i] = mean

scores 

```
    
    ii. Make a plot with the number of principal components on the _x_-axis and classification accuracy on the _y_-axis - how is this plot different from the one in Exercise 2.1.ii?
    
```{python}
plt.figure()
plt.plot(scores)
plt.xlabel('Number of principal components')
plt.ylabel('Classification accuracy')
plt.show()
```
  
The general trend is downwards.
    
    iii. What is the number of principal components, $k_{max\_accuracy}$, that results in the greatest classification accuracy when cross-validated?  
    
```{python}
np.argmax(scores) # 25
```

    iv. How many percentage points is the classification accuracy increased with relative to the to the full-dimensional, $d$, dataset 
    
```{python}
scores[25]

log_reg = LogisticRegression(penalty='none', solver='newton-cg')
#cv = StratifiedKFold(n_splits = 5) REMOVE THIS
fit_all = log_reg.fit(Z, y_all_eq)
mean_all = np.mean(score)

improvement = (scores[25])/ mean_all
improvement
```
    
    v. How do the analyses in Exercises 2.1 and 2.2 differ from one another? Make sure to comment on the differences in optimization criteria.  
3) We now make the assumption that $k_{max\_accuracy}$ is representative for each time sample (we only tested for 248 ms). We will use the PCA implementation from _scikit-learn_, i.e. import `PCA` from `sklearn.decomposition`.
    i. For __each__ of the 251 time samples, use the same estimator and cross-validation as in Exercises 2.1.i and 2.2.i. Run two analyses - one where you reduce the dimensionality to $k_{max\_accuracy}$ dimensions using `PCA` and one where you use the full data. Remember to scale the data (for now, ignore if you get some convergence warnings - you can try to increase the number of iterations, but this is not obligatory)  
    
```{python}
from sklearn.decomposition import PCA 

pca = PCA(n_components = 25)
scores_max = np.zeros(shape=(251))
log_reg = LogisticRegression(penalty='none', solver='newton-cg')
cv = StratifiedKFold(n_splits = 5)
sc = StandardScaler()

for i in range(251):
    X_time = X_all_eq[:, :, i]
    X_time_std = sc.fit_transform(X_time)
    X_pca = pca.fit_transform(X_time_std)
    log_model = log_reg.fit(X_pca, y_all_eq)
    score = cross_val_score(log_model, X_pca, y_all_eq, cv=cv)
    mean = np.mean(score)
    scores_max[i] = mean

scores_all = np.zeros(shape=(251))
log_reg = LogisticRegression(penalty='none', solver='newton-cg')
cv = StratifiedKFold(n_splits = 5)
sc = StandardScaler()

for i in range(251):
    X_time = X_all_eq[:, :, i]
    X_time_std = sc.fit_transform(X_time)
    log_model = log_reg.fit(X_time_std, y_all_eq)
    score = cross_val_score(log_model, X_time_std, y_all_eq, cv=cv)
    mean = np.mean(score)
    scores_all[i] = mean
```
    
    ii. Plot the classification accuracies for each time sample for the analysis with PCA and for the one without in the same plot. Have time (ms) on the _x_-axis and classification accuracy on the _y_-axis 
    
```{python}
plt.figure()
plt.plot(times, scores_max)
plt.plot(times, scores_all)
plt.xlabel('Time (ms)')
plt.ylabel('Classification accuracy')
plt.show()
```
    
    iii. Describe the differences between the two analyses - focus on the time interval between 0 ms and 400 ms - describe in your own words why the logistic regression performs better on the PCA-reduced dataset around the peak magnetic activity  

